import oracledb from 'oracledb';

oracledb.autoCommit = true;

let pool = null;

export async function initOracleDb() {
  if (!pool) {
    try {
      pool = await oracledb.createPool({
        user: 'system',
        password: 'oracle',
        connectString: 'localhost:1521/XEPDB1',
        poolMin: 1,
        poolMax: 5,
        poolIncrement: 1
      });
      console.log('Oracle DB pool initialized for trip logging.');
      
      const connection = await pool.getConnection();
      try {
        const createTableSql = `
          CREATE TABLE trip_logs (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            passenger_name VARCHAR2(255),
            driver_name VARCHAR2(255),
            driver_phone VARCHAR2(255),
            trip_distance NUMBER,
            trip_fare NUMBER,
            rate_description VARCHAR2(500),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
          )
        `;
        await connection.execute(createTableSql);
        console.log('Table trip_logs created successfully.');
      } catch (err) {
        // Error code ORA-00955 means the table already exists
        if (err.errorNum !== 955) {
          console.error('Error creating trip_logs table:', err);
        }
      } finally {
        await connection.close();
      }
    } catch (err) {
      console.error('Error initializing Oracle connection pool:', err);
    }
  }
}

export async function logTripToOracle(tripData) {
  try {
    if (!pool) {
      await initOracleDb();
    }
    if (!pool) return;
    
    const connection = await pool.getConnection();
    try {
      const sql = `
        INSERT INTO trip_logs 
        (passenger_name, driver_name, driver_phone, trip_distance, trip_fare, rate_description)
        VALUES (:1, :2, :3, :4, :5, :6)
      `;
      const binds = [
        tripData.passengerName || 'Rider',
        tripData.driverName || 'Driver',
        tripData.driverPhone || 'N/A',
        tripData.tripDistance || 0,
        tripData.tripFare || 0,
        tripData.rateDescription || ''
      ];
      await connection.execute(sql, binds);
      console.log('Trip successfully logged to Oracle Database.');
    } catch (err) {
      console.error('Error inserting trip into Oracle DB:', err);
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('Error in logTripToOracle:', err);
  }
}
