import oracledb from 'oracledb';

oracledb.autoCommit = true;

let pool = null;

export async function initOracleDb() {
  if (!pool) {
    try {
      pool = await oracledb.createPool({
        user: 'system',
        password: 'oracle',
        connectString: '192.168.1.29:1521/XEPDB1',
        poolMin: 1,
        poolMax: 5,
        poolIncrement: 1
      });
      console.log('Oracle DB pool initialized for trip logging.');
      
      const connection = await pool.getConnection();
      try {
        const createTableSql = `
          CREATE TABLE trip_logs (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            ride_num VARCHAR2(20),
            passenger_name VARCHAR2(255),
            passenger_username VARCHAR2(255),
            driver_name VARCHAR2(255),
            driver_phone VARCHAR2(255),
            trip_distance NUMBER,
            trip_fare NUMBER,
            rate_description VARCHAR2(500),
            status VARCHAR2(50) DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
          )
        `;
        await connection.execute(createTableSql);
        console.log('Table trip_logs created successfully.');
      } catch (err) {
        if (err.errorNum !== 955) {
          console.error('Error creating trip_logs table:', err);
        } else {
          try {
            await connection.execute(`ALTER TABLE trip_logs ADD (ride_num VARCHAR2(20) DEFAULT NULL)`);
          } catch (e) { /* column exists */ }
          try {
            await connection.execute(`ALTER TABLE trip_logs ADD (passenger_username VARCHAR2(255) DEFAULT NULL)`);
          } catch (e) { /* column exists */ }
          try {
            await connection.execute(`ALTER TABLE trip_logs ADD (updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
          } catch (e) { /* column exists */ }
        }
      } finally {
        await connection.close();
      }
    } catch (err) {
      console.error('Error initializing Oracle connection pool:', err);
    }
  }
}

export async function logTripToOracle(tripData) {
  try {
    if (!pool) {
      await initOracleDb();
    }
    if (!pool) return null;
    
    const connection = await pool.getConnection();
    try {
      const sql = `
        INSERT INTO trip_logs 
        (ride_num, passenger_name, passenger_username, driver_name, driver_phone, trip_distance, trip_fare, rate_description, status)
        VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)
        RETURNING id INTO :10
      `;
      const binds = [
        tripData.rideNum || null,
        tripData.passengerName || 'Rider',
        tripData.passengerUsername || null,
        tripData.driverName || 'N/A',
        tripData.driverPhone || 'N/A',
        tripData.tripDistance || 0,
        tripData.tripFare || 0,
        tripData.rateDescription || '',
        tripData.status || 'pending',
        { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }
      ];
      const result = await connection.execute(sql, binds);
      const insertedId = result.outBinds[0][0];
      console.log(`Trip logged to Oracle (id: ${insertedId}, status: ${tripData.status}).`);
      return insertedId;
    } catch (err) {
      console.error('Error inserting trip into Oracle DB:', err);
      return null;
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('Error in logTripToOracle:', err);
    return null;
  }
}

export async function updateTripStatus(rideNum, updates) {
  try {
    if (!pool) {
      await initOracleDb();
    }
    if (!pool) return;

    const connection = await pool.getConnection();
    try {
      const setClauses = [];
      const binds = {};

      if (updates.status) {
        setClauses.push('status = :status');
        binds.status = updates.status;
      }
      if (updates.driverName) {
        setClauses.push('driver_name = :driverName');
        binds.driverName = updates.driverName;
      }
      if (updates.driverPhone) {
        setClauses.push('driver_phone = :driverPhone');
        binds.driverPhone = updates.driverPhone;
      }
      if (updates.tripDistance !== undefined) {
        setClauses.push('trip_distance = :tripDistance');
        binds.tripDistance = updates.tripDistance;
      }
      if (updates.tripFare !== undefined) {
        setClauses.push('trip_fare = :tripFare');
        binds.tripFare = updates.tripFare;
      }
      if (updates.rateDescription) {
        setClauses.push('rate_description = :rateDescription');
        binds.rateDescription = updates.rateDescription;
      }

      setClauses.push('updated_at = CURRENT_TIMESTAMP');
      binds.rideNum = rideNum;

      const sql = `UPDATE trip_logs SET ${setClauses.join(', ')} WHERE ride_num = :rideNum AND id = (SELECT MAX(id) FROM trip_logs WHERE ride_num = :rideNum2)`;
      binds.rideNum2 = rideNum;
      
      await connection.execute(sql, binds);
      console.log(`Trip ${rideNum} updated in Oracle (status: ${updates.status}).`);
    } catch (err) {
      console.error('Error updating trip in Oracle DB:', err);
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('Error in updateTripStatus:', err);
  }
}
