import oracledb from 'oracledb';

oracledb.autoCommit = true;

let pool = null;

export async function getOracleConnection() {
  if (!pool) {
    await initOracleDb();
  }
  return pool ? await pool.getConnection() : null;
}

export async function initOracleDb() {
  if (!pool) {
    try {
      pool = await oracledb.createPool({
        user: 'system',
        password: 'oracle',
        connectString: '192.168.1.29:1521/XEPDB1',
        poolMin: 1,
        poolMax: 5,
        poolIncrement: 1
      });
      console.log('Oracle DB pool initialized.');
      
      const connection = await pool.getConnection();
      try {
        // Table for trip logs
        const createTripLogsSql = `
          CREATE TABLE trip_logs (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            passenger_name VARCHAR2(255),
            driver_name VARCHAR2(255),
            driver_phone VARCHAR2(255),
            trip_distance NUMBER,
            trip_fare NUMBER,
            rate_description VARCHAR2(500),
            status VARCHAR2(50) DEFAULT 'completed',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
          )
        `;
        await connection.execute(createTripLogsSql).catch(e => {
          if (e.errorNum !== 955) console.error(e);
        });

        await connection.execute(`ALTER TABLE trip_logs ADD status VARCHAR2(50) DEFAULT 'completed'`).catch(() => {});

        // Table for configs
        const createConfigSql = `
          CREATE TABLE app_configs (
            config_key VARCHAR2(255) PRIMARY KEY,
            config_value CLOB
          )
        `;
        await connection.execute(createConfigSql).catch(e => {
          if (e.errorNum !== 955) console.error(e);
        });

        // Table for queue jobs
        const createQueueSql = `
          CREATE TABLE queue_jobs (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            queue_type VARCHAR2(255),
            job_data CLOB,
            status VARCHAR2(50) DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            process_after TIMESTAMP,
            PRIMARY KEY (id)
          )
        `;
        await connection.execute(createQueueSql).catch(e => {
          if (e.errorNum !== 955) console.error(e);
        });

      } finally {
        await connection.close();
      }
    } catch (err) {
      console.error('Error initializing Oracle connection pool:', err);
    }
  }
}

export async function logTripToOracle(tripData) {
  try {
    const connection = await getOracleConnection();
    if (!connection) return;
    
    try {
      const sql = `
        INSERT INTO trip_logs 
        (passenger_name, driver_name, driver_phone, trip_distance, trip_fare, rate_description, status)
        VALUES (:1, :2, :3, :4, :5, :6, :7)
      `;
      const binds = [
        tripData.passengerName || 'Rider',
        tripData.driverName || 'Driver',
        tripData.driverPhone || 'N/A',
        tripData.tripDistance || 0,
        tripData.tripFare || 0,
        tripData.rateDescription || '',
        tripData.status || 'completed'
      ];
      await connection.execute(sql, binds);
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('Error in logTripToOracle:', err);
  }
}

// Config functions
export async function saveConfigToOracle(key, value) {
  try {
    const connection = await getOracleConnection();
    if (!connection) return;
    try {
      const sql = `
        MERGE INTO app_configs dest
        USING (SELECT :key AS config_key, :val AS config_value FROM dual) src
        ON (dest.config_key = src.config_key)
        WHEN MATCHED THEN UPDATE SET dest.config_value = src.config_value
        WHEN NOT MATCHED THEN INSERT (config_key, config_value) VALUES (src.config_key, src.config_value)
      `;
      await connection.execute(sql, { key, val: String(value) });
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('Error saving config to Oracle:', err);
  }
}

export async function getConfigFromOracle(key) {
  try {
    const connection = await getOracleConnection();
    if (!connection) return null;
    try {
      const sql = `SELECT config_value FROM app_configs WHERE config_key = :key`;
      const result = await connection.execute(sql, { key });
      if (result.rows && result.rows.length > 0) {
        let val = result.rows[0][0];
        if (val && typeof val.getData === 'function') { // CLOB
          val = await val.getData();
        }
        return val;
      }
      return null;
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('Error getting config from Oracle:', err);
    return null;
  }
}

// Queue functions
export async function enqueueJobOracle(type, data, delayMs = 0) {
  try {
    const connection = await getOracleConnection();
    if (!connection) {
      console.error('[ORACLE-Q] No connection available to enqueue job:', type);
      return;
    }
    try {
      const processAfter = new Date(Date.now() + delayMs);
      const sql = `
        INSERT INTO queue_jobs (queue_type, job_data, process_after)
        VALUES (:type, :data, :processAfter)
      `;
      await connection.execute(sql, { 
        type, 
        data: JSON.stringify(data), 
        processAfter 
      });
      console.log(`[ORACLE-Q] Enqueued job: type=${type}, route=${data.route || 'N/A'}, userKey=${data.userKey || 'N/A'}, delay=${delayMs}ms`);
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('[ORACLE-Q] Error enqueueing job:', type, err);
  }
}

export async function processNextJobOracle(type, callback) {
  try {
    const connection = await getOracleConnection();
    if (!connection) return null;
    try {
      // Find a pending job
      const sqlFind = `
        SELECT id, job_data FROM queue_jobs 
        WHERE queue_type = :type AND status = 'pending' AND process_after <= CURRENT_TIMESTAMP 
        ORDER BY created_at ASC FETCH FIRST 1 ROWS ONLY
      `;
      const result = await connection.execute(sqlFind, { type });
      if (result.rows && result.rows.length > 0) {
        const jobId = result.rows[0][0];
        let jobDataStr = result.rows[0][1];
        if (jobDataStr && typeof jobDataStr.getData === 'function') {
           jobDataStr = await jobDataStr.getData();
        }
        const jobData = JSON.parse(jobDataStr);

        console.log(`[ORACLE-Q] Processing job #${jobId}: type=${type}, route=${jobData.route || 'N/A'}, userKey=${jobData.userKey || 'N/A'}`);

        // Update status to processing
        await connection.execute(`UPDATE queue_jobs SET status = 'processing' WHERE id = :id`, { id: jobId });
        
        // Execute callback
        await callback({ data: jobData, type }, async () => {
           // On done, mark as completed
           try {
             const conn2 = await getOracleConnection();
             if (conn2) {
               await conn2.execute(`UPDATE queue_jobs SET status = 'completed' WHERE id = :id`, { id: jobId });
               await conn2.close();
               console.log(`[ORACLE-Q] Job #${jobId} completed: route=${jobData.route || 'N/A'}`);
             }
           } catch (doneErr) {
             console.error(`[ORACLE-Q] Error marking job #${jobId} as completed:`, doneErr);
           }
        });
        return true;
      }
      return false;
    } finally {
      await connection.close();
    }
  } catch (err) {
    console.error('[ORACLE-Q] Error processing job:', err);
    return false;
  }
}
